overlay: 1.0.0
info:
  title: Product JSON Schema German Overlay
  version: 1.0.0
  description: German localization overlay for the standalone Product JSON Schema.
extends: https://raw.githubusercontent.com/api-evangelist/products-api/main/schema/Product.yml
actions:
- target: $.description
  update: Ein mit Schema.org konformes Produktobjekt.
- target: $.properties.identifier.description
  update: Eindeutige Kennung für das Produkt.
- target: $.properties.name.description
  update: Name des Produkts.
- target: $.properties.descripton.description
  update: Die Beschreibung des Produkts.
- target: $.properties.image.description
  update: Ein Bild für die Organisation.
