overlay: 1.0.0
info:
  title: Product JSON Schema Dutch Overlay
  version: 1.0.0
  description: Dutch localization overlay for the standalone Product JSON Schema.
extends: https://raw.githubusercontent.com/api-evangelist/products-api/main/schema/Product.yml
actions:
- target: $.description
  update: Een productobject dat voldoet aan Schema.org.
- target: $.properties.identifier.description
  update: Unieke identificatiecode voor het product.
- target: $.properties.name.description
  update: Naam van het product.
- target: $.properties.descripton.description
  update: De beschrijving van het product.
- target: $.properties.image.description
  update: Een afbeelding voor de organisatie.
