generated: '2026-07-11'
method: derived
source: openapi/products-api-openapi.yml
summary:
  types:
  - apiKey
  api_key_in:
  - header
schemes:
- name: apiKeys
  type: apiKey
  in: header
  parameter: api-key
  sources:
  - openapi/products-api-openapi.yml
